upstream <?php echo $this->getSlug(); ?> {
	ip_hash;
	server 127.0.0.1:<?php echo $this->getPort(); ?>;
}

server {
  listen 80;
  server_name <?php echo $this->getSlug(); ?>.<?php echo $this->getHost(); ?>;

  location / {
    proxy_pass http://<?php echo $this->getSlug(); ?>;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header CLIENT_IP $remote_addr;
  }

}